name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
      - run: |
          npm install
          npm run build
          npm run lint
      - run: |
          cd ./demo
          npm install
          npm run build
          npm run lint
