name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
      - run: |
          npm install
          npm run build
          npm run lint
      - run: |
          cd ./demo
          npm install
          npm run build
          npm run lint
